### PR TITLE
Added mapMany and Elm-0.13's Signal.combined

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by mgold** [comment]
FWIW, I'd prefer code duplication in `combine` to an O(n) time and space no-op (mapping the identity), incurred any time any of the combined signals update.

**Comment by jvoigtlaender** [comment]
Don't know what you mean. The `map identity` that occurs in `combine = mapMany identity` is not a `List.map`, it is a `Signal.map`. Specifically, a `Signal.map identity : Signal (List a) -> Signal (List a)`. This `identity` does not traverse the list, so there is nothing O(n) here.

**Comment by jvoigtlaender** [comment]
Original discussion about these functions: https://groups.google.com/d/msg/elm-discuss/CVRhrF4Wn7k/1tOxbwvvCCAJ

**Comment by Apanatshka** [comment]
The tweak to the fairMerge docs in 1bf2dd18e148204cc5288b75141ce96f42857449 is a bit off-topic don't you think?

**Comment by jvoigtlaender** [comment]
Well, you previously had the words "without bias" as the header for the documentation section "Merge without bias". Since I added `combine` and `mapMany` to that section, that header didn't make sense anymore, so I replaced it by "Combining". To not lose the "without bias" qualification concerning `fairMerge`, I thought it made most sense to add it to the documentation of that function.

But feel free to not take this over. The "without bias" explanation would then be lost, though.

**Comment by Apanatshka** [comment]
I see. No that's fine then.

**Comment by Apanatshka** [comment]
Ok, thanks for this @jvoigtlaender :+1:

**Comment by mgold** [comment]
@jvoigtlaender Indeed, thanks for clearing up my confusion.

**Pull request merged**
