### PR TITLE
Bump version number for release to support Elm 0.16

### PR DESCRIPTION
**Pull request by rtfeldman**

### CODE REVIEW

**Comment by Apanatshka** [comment]
Thanks. I published the new version.

**Comment by rtfeldman** [comment]
Excellent, thanks! We'll most likely be using it in production next week. :smile_cat:

**Comment by Apanatshka** [comment]
Ah, so that's why I got this PR from you :smile: 
What functionality are you using from this library?

**Comment by rtfeldman** [comment]
`Signal.Time.settledAfter` - for use in a search box that sends out to a port to do full-text search via [lunr.js](http://lunrjs.com/) but doesn't want to do that whole search on every keystroke.

**Comment by rtfeldman** [comment]
By the way, it's on production now. :smiley:

**Comment by Apanatshka** [comment]
Cool :grinning: 
I think I should bite the bullet and rename those functions some day..

**Pull request merged**
