### PR TITLE
Add mergeAll

### PR DESCRIPTION
**Pull request by rtfeldman**
Adds a total version of `Signal.mergeMany`

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Alternative naming suggestions (to reflect the fact this takes one signal and a list of signals): `mergeOneAndAll`, `mergeOneAndMany`, `mergeOneAndMore`.

**Comment by Apanatshka** [comment]
@rtfeldman do you have a use case for this?
The usual use case for `mergeMany` that I have a list literal with some signals. Because the function takes and returns signals, it'll only be called once anyway and the list of signals is likely statically known.

**Comment by rtfeldman** [comment]
That's the use case I intend to use it for. Basically I want to try it out and see if it feels noticeably more or less nice than the existing partial version.

If it feels no less pleasant to use, then we have a data point about how Core could become more total with no noticeable downside. :smile:

**Comment by Apanatshka** [comment]
@rtfeldman Ok, that's good enough a reason to add it for me. Any opinions on naming?
Personally I'd prefer calling this `mergeMany`, but that clashes with `Signal`. I'm already clashing with `Signal` by defining a different version of `merge` I think, but I don't want to do it too much. So I'm not sure. I don't want to agonise over names too much, but let's think about it a little.

**Comment by rtfeldman** [comment]
Yeah I went with `mergeAll` to avoid conflicting with `mergeMany`. I haven't managed to come up with anything I like better, but totally open to suggestions!

**Comment by rehno-lindeque** [comment]
`mergeManySafe`? It says it like it is... (self-documenting in the sense that it's clearly intended as a replacement for `mergeMany`)

**Comment by rtfeldman** [comment]
I thought about that, but the default assumption is that Elm functions won't crash...usually you call them `unsafe` if they can, but obviously renaming the original is not an option in this case. :wink:

**Comment by rehno-lindeque** [comment]
But if I understand this PR the original `mergeMany` really can crash? In that case I feel as though `mergeManySafe` is the honest thing to do... I mean people trying to figure out why anyone should use `mergeAll` instead of `mergeMany` are going to come to arrive at the conclusion anyway, it'll just take more effort to figure it out.

(So, the hope is that `mergeManySafe` would be a temporary fix...)

**Comment by rtfeldman** [comment]
Ah! That's a fair point. Based on that I'm cool with mergeManySafe.

Any objections to that name?

**Comment by rgrempel** [comment]
Just a thought -- 'unsafe' is usually a prefix, so what about safeMergeMany? Though that would sort oddly.

**Comment by Apanatshka** [comment]
I'm not convinced `safeMergeMany` or `mergeManySafe` is better than just shadowing `mergeMany`. Let's just do the shadowing, this package is already opinionated.

**Comment by rtfeldman** [comment]
Works for me! Changed in https://github.com/rtfeldman/elm-signal-extra/commit/096f89396b9a3e802734f39c18e4716dba3492b2

**Comment by Apanatshka** [comment]
published as [5.5.0](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.5.0/)

**Pull request merged**
